In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [2]:
data=pd.read_csv("PerformanceRating.csv")
data.head()

PerformanceID EmployeeID ReviewDate  EnvironmentSatisfaction  \
0          PR01  79F7-78EC   1/2/2013                        5   
1          PR02  B61E-0F26   1/3/2013                        5   
2          PR03  F5E3-48BB   1/3/2013                        3   
3          PR04  0678-748A   1/4/2013                        5   
4          PR05  541F-3E19   1/4/2013                        5   

   JobSatisfaction  RelationshipSatisfaction  TrainingOpportunitiesWithinYear  \
0                4                         5                                1   
1                4                         4                                1   
2                4                         5                                3   
3                3                         2                                2   
4                2                         3                                1   

   TrainingOpportunitiesTaken  WorkLifeBalance  SelfRating  ManagerRating  
0                           0                4           4              4  
1                           3                4           4              3  
2                           2                3           5              4  
3                           0                2           3              2  
4                           0                4           4              3

In [3]:
data.isnull().sum()

PerformanceID                      0
EmployeeID                         0
ReviewDate                         0
EnvironmentSatisfaction            0
JobSatisfaction                    0
RelationshipSatisfaction           0
TrainingOpportunitiesWithinYear    0
TrainingOpportunitiesTaken         0
WorkLifeBalance                    0
SelfRating                         0
ManagerRating                      0
dtype: int64

In [4]:
data.describe()

EnvironmentSatisfaction  JobSatisfaction  RelationshipSatisfaction  \
count              6709.000000      6709.000000               6709.000000   
mean                  3.872559         3.430616                  3.427336   
std                   0.940701         1.152565                  1.156753   
min                   1.000000         1.000000                  1.000000   
25%                   3.000000         2.000000                  2.000000   
50%                   4.000000         3.000000                  3.000000   
75%                   5.000000         4.000000                  4.000000   
max                   5.000000         5.000000                  5.000000   

       TrainingOpportunitiesWithinYear  TrainingOpportunitiesTaken  \
count                      6709.000000                 6709.000000   
mean                          2.012968                    1.017290   
std                           0.820310                    0.950316   
min                           1.000000                    0.000000   
25%                           1.000000                    0.000000   
50%                           2.000000                    1.000000   
75%                           3.000000                    2.000000   
max                           3.000000                    3.000000   

       WorkLifeBalance   SelfRating  ManagerRating  
count      6709.000000  6709.000000    6709.000000  
mean          3.414667     3.984051       3.473394  
std           1.143961     0.816432       0.961738  
min           1.000000     3.000000       2.000000  
25%           2.000000     3.000000       3.000000  
50%           3.000000     4.000000       3.000000  
75%           4.000000     5.000000       4.000000  
max           5.000000     5.000000       5.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6709 entries, 0 to 6708
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   PerformanceID                    6709 non-null   object
 1   EmployeeID                       6709 non-null   object
 2   ReviewDate                       6709 non-null   object
 3   EnvironmentSatisfaction          6709 non-null   int64 
 4   JobSatisfaction                  6709 non-null   int64 
 5   RelationshipSatisfaction         6709 non-null   int64 
 6   TrainingOpportunitiesWithinYear  6709 non-null   int64 
 7   TrainingOpportunitiesTaken       6709 non-null   int64 
 8   WorkLifeBalance                  6709 non-null   int64 
 9   SelfRating                       6709 non-null   int64 
 10  ManagerRating                    6709 non-null   int64 
dtypes: int64(8), object(3)
memory usage: 576.7+ KB


In [6]:
data["ManagerRating"].unique()

array([4, 3, 2, 5], dtype=int64)

In [7]:
data["ManagerRating"].value_counts()

3    2223
4    2220
2    1192
5    1074
Name: ManagerRating, dtype: int64

In [8]:
data["SelfRating"].unique()

array([4, 5, 3], dtype=int64)

In [9]:
data["SelfRating"].value_counts()

3    2290
4    2236
5    2183
Name: SelfRating, dtype: int64

In [10]:
data["WorkLifeBalance"].unique()

array([4, 3, 2, 5, 1], dtype=int64)

In [11]:
data["WorkLifeBalance"].value_counts()

4    1706
2    1702
3    1670
5    1510
1     121
Name: WorkLifeBalance, dtype: int64

In [12]:
data["JobSatisfaction"].unique()

array([4, 3, 2, 5, 1], dtype=int64)

In [13]:
data["JobSatisfaction"].value_counts()

4    1685
2    1674
3    1651
5    1569
1     130
Name: JobSatisfaction, dtype: int64

In [14]:
data["EnvironmentSatisfaction"].unique()

array([5, 3, 4, 1, 2], dtype=int64)

In [15]:
data["EnvironmentSatisfaction"].value_counts()

3    2211
4    2175
5    2046
2     141
1     136
Name: EnvironmentSatisfaction, dtype: int64